# ignored_patterns.py
# Auto-generated by First AI Utility
# This file contains patterns that should be ignored/flagged during processing

IGNORED_MODEL_PATTERNS = [
]

IGNORED_QA_NUMBER_PATTERNS = [
]

IGNORED_AUTHOR_PATTERNS = [
]

IGNORED_TOPIC_PATTERNS = [
]

# Note: Patterns added here will be flagged in RED during document review
# Use exact match patterns (^...$) for specific items
# Or use partial patterns for broader matching